---
title: "Borrowings from Arabic, Persian and Turkic languages to Daghestan languages"
output: html_document
---

Here will be the main goals and objectives of the project, how to quote, participants and other information

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = '')
library(RefManageR)
BibOptions(check.entries = FALSE, style = 'text', bib.style = 'authoryear')
article_citation <- BibEntry(bibtype = 'Book', 
 key='dagapt2022',
 title='DAG <- APT, An online database of borrowed vocabulary in the languages of Daghestan, v. 1.0.0',
 author='S. Verhees, T. Dedov',
 year='2022',
 publisher='Linguistic Convergence Laboratory, NRU HSE',
 address='Moscow',
 url='http://lingconlab.ru/dagatlas')
```

## How to cite {.tabset .tabset-fade .tabset-pills} 

### Plain text
```{r, results = 'asis'}
print(article_citation, .opts = list(style = 'text', max.names = 15))
```

### BibTeX

```{r}
print(article_citation, .opts = list(style = 'Bibtex'))
```
# Contacts
Please contact Timofei Dedov (tgdedov@gmail.com) in case you have any inquiries about the data or there is a technical issue