project:
  type: website
  title: "DAG-APT"
  output-dir: ./../docs/ru
  render:
  - index.qmd
  - database.qmd
  - donor_lexems.qmd
  - sources.qmd
  
website:
  title: "DAG-APT"
  navbar:
    pinned: true
    right:
    - text: en
      href: ./../index.html
    left:
      - href: index.qmd
        text: главная
      - href: database.qmd
        text: "база данных"
      - href: donor_lexems.qmd
        text: "лексемы"
      - href: sources.qmd
        text: "литература"
lang: ru
execute:
  echo: false
  warning: false
  message: false
format:
  html:
    theme: flatly
    linkcolor: '#2c3e50'
    header-includes: <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap"
      rel="stylesheet">

editor: visual



